### ISSUE TITLE
Use DHCP option for log server?

### ISSUE THREAD

**Issue by TomKeddie** [TheStaticTurtle/esphome_syslog#1]
Hi, thanks for this component.  I've burnt it onto a few esp8266 based modules and it seems to work well.  Given udp is stateless and things would have to be really broken for the packet to not send it seems fairly low risk.

I just realised I now need to migrate to a different subnet and will need to reprogram my modules for them to report syslog.  Am wondering if it's possible to grab the log server from a dhcp option?   See http://www.networksorcery.com/enp/protocol/bootp/option007.htm

**Comment by TheStaticTurtle** [comment]
It seems to be possible but would require quite a lot of work including recompiling the espX core to support the DHCP syslog option from what I see only the NTP option (which is handled internally and sets the server automatically) is enabled/developed in the core.

This would also mean using a special core for each type of device (esp8266, esp32) and I have no idea if you could even select a custom core from esphome.

Apart if I missed something obvious. It seems a like lot of work for not a lot of gain, I would suggest just to set the ip of the server in the config, I realize it isn't ideal, but I don't have time to investigate the DHCP options further.

I've just now realized, but since you are in a different subnet (with all your IoT stuff I presume) why not set the IP to 255.255.255.255 this would broadcast the syslog packets to everyone on the network and should still reach the server no matter it's ip address. As I said it isn't ideal, but it could work since you are in a different subnet

**Comment by TomKeddie** [comment]
Thanks, I hadn't taken the time to look at the code, was hoping the options would be readily available.  Thanks for this module, I'll just update my configs.
